### ISSUE TITLE
Proper Asset File Type

### ISSUE THREAD

**Issue by McCallisterRomer** [NcStudios/NcEngine#234]
The .nca file type should be reworked:
* Should have a proper header with version, type, etc.
* Data should be binary - not sure if supporting a human readable version has utility...
* Binary blobs should be compressed: lz4 is fine to start, but we should be forward thinking and allow specifying compression type in the header.

**Comment by ClickerMonkey** [comment]
> Data should be binary - not sure if supporting a human readable version has utility...

It's common for there to be a format that merges well so repos can keep track of changes. This may be an intermediary format that's stored in the repo, but on commit to main branch they are converted to binary version when a playable game build is made. If each build can be traced to a commit then a QA team can identify when a bug was introduced and if the data in the repo is human readable it can be more easily determined.

Just what I've heard from people talk about the subject and something I've tried to do!
