### ISSUE TITLE
 vulkan memory allocator not compatible with latest vulkan sdk

### ISSUE THREAD

**Issue by CitroenGames** [NcStudios/NcEngine#684]
vulkan sdk 1.3.290.0 is not compatible with the included vulkan memory allocator
![image](https://github.com/user-attachments/assets/3d637511-fc41-4116-8077-bbb9af5b05e7)

to solve it you have to downgrade from 1.3.2.690.0 but this wont work forever because eventually the download for this version will disappear

**Comment by McCallisterRomer** [comment]
Thanks for pointing this out! The vma hpp bindings have been a slight nuisance in the past. Since the VulkanSDK can optionally include the C header for vma, we're going to switch to the C API. We'll attempt to target whatever header the sdk installation laid down, with a fallback in place.
